# Generated by Django 4.2.1 on 2023-11-04 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import g_bbs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBlockWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='不適切な単語')),
            ],
        ),
        migrations.CreateModel(
            name='BlockWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('is_oneword', models.BooleanField(default=False)),
                ('json_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='G_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='G投稿日時')),
                ('g_comment', models.CharField(max_length=2000, validators=[g_bbs.models.validate_bad_word], verbose_name='Gコメント')),
                ('g_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Replyg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_comment', models.CharField(max_length=2000, verbose_name='コメント')),
                ('g_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g_bbs.g_topic', verbose_name='リプライ対象のGトピック')),
            ],
        ),
    ]
